---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "cos-fleetshard-test-harness"
  namespace: "rhoc"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "cos-fleetshard-test-harness"
  namespace: "rhoc"
rules:
  - apiGroups:
    - "apiextensions.k8s.io"
    resources:
    - "customresourcedefinitions"
    verbs:
    - "get"
    - "list"
    - "watch"
  - apiGroups:
    - "cos.bf2.org"
    resources:
    - "managedconnectors"
    - "managedconnectorclusters"
    - "managedconnectoroperators"
    verbs:
    - "get"
    - "list"
    - "watch"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "cos-fleetshard-test-harness"
  namespace: "rhoc"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "cos-fleetshard-test-harness"
subjects:
  - kind: "ServiceAccount"
    name: "cos-fleetshard-test-harness"
    namespace: "rhoc"
---
apiVersion: "v1"
kind: "Pod"
metadata:
  name: cos-fleetshard-test-harness
  namespace: "rhoc"
spec:
  containers:
    - name: cos-fleetshard-test-harness
      image: quay.io/abrianik/cos-fleetshard-test-harness
      imagePullPolicy: Always
  restartPolicy: Never
  serviceAccountName: "cos-fleetshard-test-harness"
